packages:
  - deploy/migration

allowBuilds:
  "@prisma/engines": true
  esbuild: true
  prisma: true
  sharp: false
  unrs-resolver: false
engineStrict: true
injectWorkspacePackages: true
overrides:
  deepmerge-ts: 8.0.1
  mysql2: 3.22.0
